FROM ubuntu:16.04

RUN apt-get update \
    && apt-get install -y python2.7 python3 \
    && apt-get install -y python-pip python3-pip  \
    && pip3 install --upgrade pip \
    && export AIRFLOW_HOME=~/airflow \
    && pip3 install apache-airflow \
    && pip3 install apache-airflow[crypto] \
    && cd ~/airflow
    && mkdir dags
    && apt-get install -y vim 
